abbrevs:
  - name: neovim
    abbr: v
    snippet: nvim
  - name: tmux
    abbr: t
    snippet: tmux
  - name: tmux new session
    abbr: n
    snippet: 'new -s "{}"'
    global: true
    context: "^tmux "
  - name: clear
    abbr: c
    snippet: clear
  - name: ..
    abbr: ..
    snippet: "cd .."
  - name: lazygit
    abbr: lg
    snippet: lazygit
  - name: ghq
    abbr: gg
    snippet: "ghq get"
